code/src/br/ufes/inf/nemo/marvin/core/application/InstallSystemServiceBean.java
package br.ufes.inf.nemo.marvin.core.application;

import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.inf.nemo.marvin.core.domain.Academic;
import br.ufes.inf.nemo.marvin.core.domain.AcademicType;
import br.ufes.inf.nemo.marvin.core.domain.MarvinConfiguration;
import br.ufes.inf.nemo.marvin.core.exceptions.SystemInstallFailedException;
import br.ufes.inf.nemo.marvin.core.persistence.AcademicDAO;
import br.ufes.inf.nemo.marvin.core.persistence.MarvinConfigurationDAO;
import br.ufes.inf.nemo.util.TextUtils;

/**
 * TODO: document this type.
 *
 * @author Vítor E. Silva Souza (vitorsouza@gmail.com)
 * @version 1.0
 */
@Stateless
public class InstallSystemServiceBean implements InstallSystemService {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** The logger. */
	private static final Logger logger = Logger.getLogger(InstallSystemServiceBean.class.getCanonicalName());

	/** The DAO for Academic objects. */
	@EJB
	private AcademicDAO academicDAO;
	
	/** The DAO for MarvinConfiguration objects. */
	@EJB
	private MarvinConfigurationDAO marvinConfigurationDAO;

	/** Global information about the application. */
	@EJB
	private CoreInformation coreInformation;

	/** @see br.ufes.inf.nemo.marvin.core.application.InstallSystemService#installSystem(br.ufes.inf.nemo.marvin.core.domain.MarvinConfiguration, br.ufes.inf.nemo.marvin.core.domain.Academic) */
	@Override
	public void installSystem(MarvinConfiguration config, Academic admin) throws SystemInstallFailedException {
		logger.log(Level.FINER, "Installing system...");

		try {
			// Encodes the admin's password.
			admin.setPassword(TextUtils.produceMd5Hash(admin.getPassword()));
			
			// Register the last update date / creation date.
			Date now = new Date(System.currentTimeMillis());
			admin.setLastUpdateDate(now);
			admin.setCreationDate(now);
			config.setCreationDate(now);
			admin.setAcademicTypes(new ArrayList<AcademicType>());
			admin.getAcademicTypes().add(AcademicType.Admin);
			admin.getAcademicTypes().add(AcademicType.Teacher);
			
			logger.log(Level.FINE, "Admin's last update date have been set as: {0}", new Object[] { now });
			
			// Saves the administrator.
			logger.log(Level.FINER, "Persisting admin data...\n\t- Short name = {0}\n\t- Last update date = {1}", new Object[] { admin.getShortName(), admin.getLastUpdateDate() });
			academicDAO.save(admin);
			logger.log(Level.FINE, "The administrator has been saved: {0} ({1})", new Object[] { admin.getName(), admin.getEmail() });
			
			// Saves Marvin's configuration.
			logger.log(Level.FINER, "Persisting configuration data...\n\t- Date = {0}\n\t- Acronym = {1}", new Object[] { config.getCreationDate(), config.getInstitutionAcronym() });
			marvinConfigurationDAO.save(config);
			logger.log(Level.FINE, "The configuration has been saved");
			
			// Reloads the bean that holds the configuration and determines if the system is installed.
			logger.log(Level.FINER, "Reloading core information...");
			coreInformation.init();
		}		
		catch (NoSuchAlgorithmException e) {
			// Logs and rethrows the exception for the controller to display the error to the user.
			logger.log(Level.SEVERE, "Could not find MD5 algorithm for password encription!", e);
			throw new SystemInstallFailedException(e);
		}
		catch (Exception e) {
			// Logs and rethrows the exception for the controller to display the error to the user.
			logger.log(Level.SEVERE, "Exception during system installation!", e);
			throw new SystemInstallFailedException(e);
		}
	}

}

code/src/br/ufes/inf/nemo/marvin/core/application/ManageAcademicsServiceBean.java
package br.ufes.inf.nemo.marvin.core.application;

import java.security.NoSuchAlgorithmException;
import java.util.Date;

import javax.annotation.security.DeclareRoles;
import javax.annotation.security.PermitAll;
import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Stateless;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;

import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.MultiPartEmail;

import br.ufes.inf.nemo.marvin.core.domain.Academic;
import br.ufes.inf.nemo.marvin.core.domain.MarvinConfiguration;
import br.ufes.inf.nemo.marvin.core.persistence.AcademicDAO;
import br.ufes.inf.nemo.jbutler.TextUtils;
import br.ufes.inf.nemo.jbutler.ejb.application.CrudException;
import br.ufes.inf.nemo.jbutler.ejb.application.CrudServiceBean;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;

@Stateless
@DeclareRoles({ "Admin" , "Alumni" , "Researcher" , "Student" , "Teacher" })
@RolesAllowed({ "Admin" })
//@PermitAll
public class ManageAcademicsServiceBean extends CrudServiceBean<Academic> implements ManageAcademicsService{

	/** Serialization id. */
	private static final long serialVersionUID = 1L;
	
	
	/** The DAO for Academic objects. */
	@EJB
	private AcademicDAO academicDAO;
	
	
	/** The information singleton for the core module. */
	@EJB    	
	private CoreInformation coreInformation;
	
	
	
	
	@Override
	public BaseDAO<Academic> getDAO() {
		return academicDAO;
	}
	
	
	@Override
	public void validateUpdate(Academic entity) throws CrudException {
		Date now = new Date(System.currentTimeMillis());
		entity.setLastUpdateDate(now);
	}
	
	@Override
	public void validateCreate(Academic entity) throws CrudException {
		Date now = new Date(System.currentTimeMillis());
		entity.setLastUpdateDate(now);
		entity.setCreationDate(now);
		sendEmailRegister(entity);
		try {
			entity.setPassword(TextUtils.produceMd5Hash(entity.getPassword()));
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
	}
	
	
	@Override
	public void sendEmailRegister(Academic entity){
		
		MultiPartEmail email;
		HttpServletRequest origRequest = (HttpServletRequest)FacesContext.getCurrentInstance().getExternalContext().getRequest();
		
		String emailAddress = entity.getEmail();
		emailAddress = "manzoli2122@gmail.com";
		MarvinConfiguration config = coreInformation.getCurrentConfig(); 
		
		String msg = "Bem Vindo Ao Sistema Marvin, ele agrega ferramentas úteis para o gerenciamento de tarefas de ensino e pesquisa em uma universidade. \n\n"
				+ "para realizar o primeiro acesso entre na pagina \n"
				+ origRequest.getRequestURL().substring(0, origRequest.getRequestURL().indexOf(origRequest.getServletPath())) + "\n"
				+ "para realizar login entra com seu email, sua senha inicial será: \n"
				+ entity.getPassword();
		
		try{
			 email = new MultiPartEmail();
			 email.setHostName(config.getSmtpServerAddress());
			 email.setSmtpPort(config.getSmtpServerPort());
			 email.setAuthenticator(new DefaultAuthenticator(config.getSmtpUsername(), config.getSmtpPassword()));
			 email.setTLS(true);
			 //email.setSSL(true);
			 email.setFrom(config.getSmtpUsername());
			 email.setSubject("Cadastro Sistema Marvin-UFES");
			 email.setMsg(msg);
			 email.addTo(emailAddress);
			 email.addTo(config.getSmtpUsername());
			 email.send();
		
		}
		catch (EmailException e) {
			e.printStackTrace();
		}	
		
		
		
		
	}
	
	
}

code/src/br/ufes/inf/nemo/marvin/core/application/ManageCourseServiceBean.java
package br.ufes.inf.nemo.marvin.core.application;

import javax.annotation.security.DeclareRoles;
import javax.annotation.security.RolesAllowed;
import javax.ejb.EJB;
import javax.ejb.Stateless;

import br.ufes.inf.nemo.marvin.core.domain.Course;
import br.ufes.inf.nemo.marvin.core.persistence.CourseDAO;
import br.ufes.inf.nemo.jbutler.ejb.application.CrudException;
import br.ufes.inf.nemo.jbutler.ejb.application.CrudServiceBean;
import br.ufes.inf.nemo.jbutler.ejb.persistence.BaseDAO;


/**
 * Stateless session bean implementing the "Manage Course" use case component. See the implemented interface
 * documentation for details.
 * 
 * @author Bruno Manzoli (manzoli2122@gmail.com)
 * @see sae.core.application.ManageAdministradorService
 */
@Stateless
@DeclareRoles({ "Admin" , "Alumni" , "Researcher" , "Student" , "Teacher" })
@RolesAllowed({ "Admin" })
public class ManageCourseServiceBean extends CrudServiceBean<Course> implements ManageCourseService{

	
	/** Serialization id. */
	private static final long serialVersionUID = 1L;
	
	
	/** The DAO for Course objects. */
	@EJB
	private CourseDAO courseDAO;

	
	
	/** @see br.ufes.inf.nemo.util.ejb3.application.CrudService#getDAO() */
	@Override
	public BaseDAO<Course> getDAO() {
		return courseDAO;
	}
	
	
	/** @see sae.core.application.CrudServiceBean#validateUpdate(Course entity) */
	@Override
	public void validateUpdate(Course entity) throws CrudException {
		Course oldEntity = getDAO().retrieveById(entity.getId());
		if (!oldEntity.getName().equals(entity.getName())){
			throw new CrudException(null, null, null);
		}
	}


}

code/src/br/ufes/inf/nemo/marvin/core/application/SessionInformationBean.java
package br.ufes.inf.nemo.marvin.core.application;

import java.security.NoSuchAlgorithmException;
import java.security.Principal;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.ejb.EJBTransactionRolledbackException;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.SessionScoped;

import br.ufes.inf.nemo.marvin.core.domain.Academic;
import br.ufes.inf.nemo.marvin.core.domain.AcademicType;
import br.ufes.inf.nemo.marvin.core.exceptions.LoginFailedException;
import br.ufes.inf.nemo.marvin.core.persistence.AcademicDAO;
import br.ufes.inf.nemo.util.TextUtils;
import br.ufes.inf.nemo.jbutler.ejb.persistence.exceptions.MultiplePersistentObjectsFoundException;
import br.ufes.inf.nemo.jbutler.ejb.persistence.exceptions.PersistentObjectNotFoundException;

/**
 * Stateful session bean implementing the session information component. See the implemented interface documentation for
 * details.
 * 
 * @author Vitor E. Silva Souza (vitorsouza@gmail.com)
 * @see br.org.feees.sigme.core.application.SessionInformation
 */
@SessionScoped
@Stateful
public class SessionInformationBean implements SessionInformation {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;

	/** The logger. */
	private static final Logger logger = Logger.getLogger(SessionInformationBean.class.getCanonicalName());

	
	
	/** The DAO for Academic objects. */
	@EJB
	private AcademicDAO academicDAO;

	
	@Resource 	
	private SessionContext sessionC;
	
	
	/** The current user logged in. */
	private Academic currentUser;

	
	
	/** @see br.org.feees.sigme.core.application.SessionInformation#getCurrentUser() */
	@Override
	public Academic getCurrentUser() {
		if( currentUser == null ){
			Principal principal = sessionC.getCallerPrincipal();
			if(principal != null){
				if(principal.getName()!=null){
					try { 
						currentUser = academicDAO.retrieveByEmail(principal.getName());
					} 
					catch (PersistentObjectNotFoundException | MultiplePersistentObjectsFoundException e) {
						currentUser = null ;
					}
				}
			}
		}
		return currentUser;
	}



	@Override
	public boolean isAdmin() {
		if(getCurrentUser()!=null){
			if(currentUser.getAcademicTypes().contains(AcademicType.Admin)){
				return true;
			}
		}
		return false;
	}



	@Override
	public boolean isAlumni() {
		if(getCurrentUser()!=null){
			if(currentUser.getAcademicTypes().contains(AcademicType.Alumni)){
				return true;
			}
		}
		return false;
	}



	@Override
	public boolean isStudent() {
		if(getCurrentUser()!=null){
			if(currentUser.getAcademicTypes().contains(AcademicType.Student)){
				return true;
			}
		}
		return false;
	}



	@Override
	public boolean isResearcher() {
		if(getCurrentUser()!=null){
			if(currentUser.getAcademicTypes().contains(AcademicType.Researcher)){
				return true;
			}
		}
		return false;
	}



	@Override
	public boolean isTeacher() {
		if(getCurrentUser()!=null){
			if(currentUser.getAcademicTypes().contains(AcademicType.Teacher)){
				return true;
			}
		}
		return false;
	}

	
	
	
	
	
	
	
	
	/** @see br.org.feees.sigme.core.application.SessionInformation#login(java.lang.String, java.lang.String) */
	/*
	@Override
	public void login(String username, String password) throws LoginFailedException {
		try {
			// Obtains the user given the e-mail address (that serves as username).
			logger.log(Level.FINER, "Authenticating user with username \"{0}\"...", username);
			Academic user = academicDAO.retrieveByEmail(username);

			// Creates the MD5 hash of the password for comparison.
			String md5pwd = TextUtils.produceMd5Hash(password);

			// Checks if the passwords match.
			String pwd = user.getPassword();
			if ((pwd != null) && (pwd.equals(md5pwd))) {
				logger.log(Level.FINEST, "Passwords match for user \"{0}\".", username);

				// Login successful. Registers the current user in the session.
				logger.log(Level.FINE, "Academic \"{0}\" successfully logged in.", username);
				currentUser = user;
				pwd = null;

				// Registers the user login.
				Date now = new Date(System.currentTimeMillis());
				logger.log(Level.FINER, "Setting last login date for academic with username \"{0}\" as \"{1}\"...", new Object[] { currentUser.getEmail(), now });
				currentUser.setLastLoginDate(now);
				academicDAO.save(currentUser);
			}
			else {
				// Passwords don't match.
				logger.log(Level.INFO, "Academic \"{0}\" not logged in: password didn't match.", username);
				throw new LoginFailedException(LoginFailedException.LoginFailedReason.INCORRECT_PASSWORD);
			}
		}
		catch (PersistentObjectNotFoundException e) {
			// No academic was found with the given username.
			logger.log(Level.INFO, "User \"{0}\" not logged in: no registered academic found with given username.", username);
			throw new LoginFailedException(e, LoginFailedException.LoginFailedReason.UNKNOWN_USERNAME);
		}
		catch (MultiplePersistentObjectsFoundException e) {
			// Multiple academics were found with the same username.
			logger.log(Level.WARNING, "User \"{0}\" not logged in: there are more than one registered academic with the given username.", username);
			throw new LoginFailedException(e, LoginFailedException.LoginFailedReason.MULTIPLE_USERS);
		}
		catch (EJBTransactionRolledbackException e) {
			// Unknown original cause. Throw the EJB exception.
			logger.log(Level.WARNING, "User \"" + username + "\" not logged in: unknown cause.", e);
			throw e;
		}
		catch (NoSuchAlgorithmException e) {
			// No MD5 hash generation algorithm found by the JVM.
			logger.log(Level.SEVERE, "Logging in user \"" + username + "\" triggered an exception during MD5 hash generation.", e);
			throw new LoginFailedException(LoginFailedException.LoginFailedReason.MD5_ERROR);
		}
	}
	*/
	
	
}

code/src/br/ufes/inf/nemo/marvin/core/controller/CoreController.java
package br.ufes.inf.nemo.marvin.core.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.ejb.EJB;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.convert.Converter;
import javax.inject.Named;

import br.ufes.inf.nemo.jbutler.ejb.controller.PersistentObjectConverterFromId;
import br.ufes.inf.nemo.marvin.core.domain.Academic;
import br.ufes.inf.nemo.marvin.core.domain.AcademicType;
import br.ufes.inf.nemo.marvin.core.domain.Course;
import br.ufes.inf.nemo.marvin.core.persistence.AcademicDAO;
import br.ufes.inf.nemo.marvin.core.persistence.CourseDAO;




@Named
@ApplicationScoped
public class CoreController implements Serializable{


	private static final long serialVersionUID = 1L;

	
	/** The DAO for Academic objects. */
	@EJB    	
	private AcademicDAO academicDAO;
	
	
	@EJB    	
	private CourseDAO courseDAO;
	
	
	
	
	
	
	/** JSF Converter for Academic objects. */
	private PersistentObjectConverterFromId<Academic> academicConverter;
	
	
	/** JSF Converter for Course objects. */
	private PersistentObjectConverterFromId<Course> courseConverter;
	
	
	
	
	
	
	/** Getter for courseConverter */
	public Converter getCourseConverter() {
		if (courseConverter == null) {
			courseConverter = new PersistentObjectConverterFromId<Course>(courseDAO);
		}
		return courseConverter;
	}
	
	
	/** Getter for AcademicConverter */
	public Converter getAcademicConverter() {
		if (academicConverter == null) {
			academicConverter = new PersistentObjectConverterFromId<Academic>(academicDAO);
			
		}
		return academicConverter;
	}
	
	
	

	
	
	
	public List<Academic> getTeachers(){
		List<Academic> lista = academicDAO.retrieveAll();
		List<Academic> teacher = new ArrayList<Academic>();
		for(Academic academic : lista){
			Iterator<AcademicType> it = academic.getAcademicTypes().iterator();
			while(it.hasNext()){
				if(it.next().equals(AcademicType.Teacher)){
					teacher.add(academic);
				}
			}
		}
		return teacher;
	}
	
	
	public List<Academic> getAlumnis(){
		List<Academic> lista = academicDAO.retrieveAll();
		List<Academic> alumni = new ArrayList<Academic>();
		for(Academic academic : lista){
			Iterator<AcademicType> it = academic.getAcademicTypes().iterator();
			while(it.hasNext()){
				if(it.next().equals(AcademicType.Alumni)){
					alumni.add(academic);
				}
			}
		}
		return alumni;
	}
	
	
	
	
	public List<Course> getCourses(){
		return courseDAO.retrieveAll();
	}
	
	
	
	
	
	public String login(){
		return "/login/index.xhtml?faces-redirect=true" ;
	}
	
	
	
	
	public AcademicType[] getAcademicType() {
		return AcademicType.values();
	}
	
	
	
}

code/WebContent/sae/core/manageSeminars/form.xhtml
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:p="http://primefaces.org/ui"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                xmlns:jsf="http://xmlns.jcp.org/jsf"
                template="/resources/#{coreInfo.decorator}/decorator.xhtml">

<ui:define name="title"> 
	<h:outputText value="#{msgsSAE['manageSeminars.title.create']}" 
				  rendered="#{(! manageSeminarsControl.readOnly) and (manageSeminarsControl.selectedEntity.id == null)}" />
   	<h:outputText value="#{msgsSAE['manageSeminars.title.update']}" 
   		          rendered="#{(! manageSeminarsControl.readOnly) and (manageSeminarsControl.selectedEntity.id != null)}" />
    <h:outputText value="#{msgsSAE['manageSeminars.title.retrieve']}" rendered="#{manageSeminarsControl.readOnly}" />
</ui:define>
	
<ui:define name="body">
				
	<ui:decorate template="/resources/#{coreInfo.decorator}/form.xhtml">
		<ui:param name="formName" value="form" /> 
		<ui:param name="formLabel" value="#{msgsSAE['manageSeminars.title.form']}" />
		
		<ui:decorate template="/resources/#{coreInfo.decorator}/formfield.xhtml">
			<ui:param name="fieldName" value="title"/>
			<ui:param name="label" value="#{msgsSAE['manageSeminars.title.title']}"/>
					<p:inputText required="true" id="title" pt:class="form-control" disabled="#{manageSeminarsControl.readOnly}" 
								 pt:placeholder="#{msgsSAE['manageSeminars.title.title']}" value="#{manageSeminarsControl.selectedEntity.title}">
						<p:ajax event="blur" update="titleField" />
					</p:inputText>
		</ui:decorate>
		
		
		
		<ui:decorate template="/resources/#{coreInfo.decorator}/formfield.xhtml">
			<ui:param name="fieldName" value="topicOfInterest"/>
			<ui:param name="label" value="#{msgsSAE['manageSeminars.title.topicOfInterest']}"/>
					<h:selectOneMenu pt:class="form-control"  id="topicOfInterest" value="#{manageSeminarsControl.selectedEntity.topicOfInterest}" 
									 converter="#{coreSaeControl.topicOfInterestConverter}" required="true" 
									 disabled="#{manageSeminarsControl.readOnly}">
						<f:selectItem itemLabel="#{msgsSAE['manageSeminars.form.topicsOfInterest.blankOption']}" itemValue="" />
						<f:selectItems value="#{manageTopicsOfInterestControl.entities}" var="topicOfInterest" itemLabel="#{topicOfInterest.name}" 
									   itemValue="#{topicOfInterest}"/>
						<p:ajax  update="topicOfInterestField" />
					</h:selectOneMenu>
		</ui:decorate>
		
		<ui:decorate template="/resources/#{coreInfo.decorator}/formfield.xhtml">
			<ui:param name="fieldName" value="alumni"/>
			<ui:param name="label" value="#{msgsSAE['manageSeminars.title.panelistAlumni']}"/>	
					<h:selectOneMenu pt:class="form-control"  id="alumni" value="#{manageSeminarsControl.selectedEntity.alumni_panelist}" 
									 converter="#{coreController.academicConverter}"  
									 disabled="#{(manageSeminarsControl.readOnly)}">
						<f:selectItem itemLabel="#{msgsSAE['manageSeminars.form.alumni.blankOption']}" itemValue="" />
						<f:selectItems value="#{coreController.alumnis}" var="alumni" itemLabel="#{alumni.name}" 
									   itemValue="#{alumni}" />
						<p:ajax  update="alumniField panelistField" />
					</h:selectOneMenu>
		</ui:decorate>
		
		
		<ui:decorate template="/resources/#{coreInfo.decorator}/formfield.xhtml">
			<ui:param name="fieldName" value="panelist"/>
			<ui:param name="label" value="#{msgsSAE['manageSeminars.title.panelist']}"/>	
					<p:inputText  disabled="#{manageSeminarsControl.readOnly}" pt:placeholder="#{msgsSAE['manageSeminars.title.panelist']}"
								  id="panelist" value="#{manageSeminarsControl.selectedEntity.panelist}" pt:class="form-control">
						<p:ajax event="blur" update="panelistField" />
					</p:inputText>
		</ui:decorate>
		
		<ui:decorate template="/resources/#{coreInfo.decorator}/formfield.xhtml">
			<ui:param name="fieldName" value="place"/>
			<ui:param name="label" value="#{msgsSAE['manageSeminars.title.place']}"/>		
					<p:inputText id="place" pt:class="form-control" disabled="#{manageSeminarsControl.readOnly}" 
								 pt:placeholder="#{msgsSAE['manageSeminars.title.place']}" value="#{manageSeminarsControl.selectedEntity.place}">
						<p:ajax event="blur" update="placeField" />
					</p:inputText>
		</ui:decorate>
		
		
		
		<ui:decorate template="/resources/#{coreInfo.decorator}/formfield.xhtml">
			<ui:param name="fieldName" value="date_time"/>
			<ui:param name="label" value="#{msgsSAE['manageSeminars.title.date_time']}"/>
					<p:inputMask id="date_time" pt:class="form-control" value="#{manageSeminarsControl.selectedEntity.date_time}"
			           			 mask="#{msgs['format.datetime.primefaces']}" disabled="#{manageSeminarsControl.readOnly}">
						<f:convertDateTime type="date" pattern="#{msgs['format.datetime.java']}" locale="pt_BR" 
										   timeZone="America/Sao_Paulo"/>
					</p:inputMask>
		</ui:decorate>
		
		
		
		
		
		<ui:decorate template="/resources/#{coreInfo.decorator}/formbuttonpanel-03.xhtml">
	        	<p:commandButton pt:class="btn btn-block btn-success btn-social" action="#{manageSeminarsControl.confirmar()}" icon="fa fa-file-text" disabled="#{manageSeminarsControl.readOnly}" value="#{msgsSAE['manageSeminars.button.confirmar']}"/>      	
	        	<p:commandButton pt:class="btn btn-block btn-info btn-social" action="#{manageSeminarsControl.save}" update=":globalMessages form" disabled="#{manageSeminarsControl.readOnly}" icon="fa fa-save" value="#{msgs['crud.button.save']}"/>
	        	<p:commandButton pt:class="btn btn-block btn-warning btn-social" immediate="true" action="#{manageSeminarsControl.list}" icon="fa fa-rotate-left" disabled="#{manageSeminarsControl.selectedEntity == null}" value="#{msgs['crud.button.back']}"/>
	    </ui:decorate>	
						
	</ui:decorate>
	
</ui:define>
</ui:composition>